#!/bin/bash

### Apps
# Terminal emulator
super + Return
    kitty

# Other applications
super + {_, shift + }w
    firefox{_, --private-window}

super + e
    subl --launch-or-new-window

super + d
    pcmanfm

super + s
    firefox home.local

super + g
    ~/bin/dmenu-gitclones

super + F2
    kitty btop


### Menus

# App and run Menu
super + {_, shift + }@space
    rofi -show {drun, run}

# Power Menu
super + Delete
	rofi -show power-menu -modi "power-menu:/home/albert/.config/rofi/rofi-power-menu"

super + F1
    slock

### Utilities

# Reload wallpaper
super + F5
	~/.fehbg &

# Reload monitors
super + F6
    $HOME/bin/monitors
	
# Reload sxhkd
super + F7
    pkill -USR1 -x sxhkd

# Notification daemon
super + {_, shift + }Pause
    {dunstctl close-all, $HOME/bin/toggle-dunst}

### Media keys

XF86AudioRaiseVolume
    pamixer --allow-boost -i 1

XF86AudioLowerVolume
    pamixer --allow-boost -d 1

XF86AudioMute
    pamixer -t

XF86MonBrightnessDown
    brightnessctl -e -d intel_backlight set '5%-'

XF86MonBrightnessUp
    brightnessctl -e -d intel_backlight set '+5%'

XF86Sleep
    systemctl suspend

XF86AudioPlay
    playerctl play-pause
        
XF86AudioNext
    playerctl next

XF86AudioPrev
    playerctl previous

XF86AudioStop
    playerctl stop

XF86WebCam
    sed -i 's/card [0-9]/card {0,1}/' $HOME/.asoundrc

XF86TouchpadToggle
    $HOME/bin/toggle-touchpad

Print
    flameshot gui
